sudo: required

services: 
    - docker

before_install:
    - docker build -t ramji2406/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ramji2406/docker-react npm run test -- --coverage

language:
    - generic